// Mock data for Companies Page
export type CompanySize = 'startup' | 'small' | 'medium' | 'large' | 'enterprise';
export type CompanyCulture = 'startup' | 'corporate' | 'innovative' | 'supportive';
export type BusinessType = 'technology' | 'retail' | 'food' | 'fashion' | 'finance' | 'healthcare' | 'education' | 'service';
export type EmploymentType = 'full-time' | 'part-time' | 'internship';

export interface Company {
  id: string;
  name: string;
  logo: string;
  coverImage: string;
  description: string;
  industry: string[];
  location: string;
  latitude: number;
  longitude: number;
  size: CompanySize;
  culture: CompanyCulture;
  businessType: BusinessType;
  employmentType: EmploymentType[];
  foundedDate: string;
  website: string;
  rating: number;
  totalReviews: number;
  views: number;
  followersCount?: number;
  isFollowing?: boolean;
  tags?: string[];

  // Company Info
  aboutCompany: string;
  mission: string;
  vision: string;
  companyHistory: {
    year: string;
    milestone: string;
  }[];

  // Jobs
  openPositions: number;
  jobCategories: string[];

  // Salary
  salaryRange: [number, number]; // in millions
  salaryByRole?: {
    role: string;
    min: number;
    max: number;
  }[];

  // Benefits & Policies
  benefits: string[];
  workingHours: string;
  offDays: number;
  overTimePolicy: string;
  vacationDays: number;
  insurances: string[];
  salaryBenefits: string[];
  allowances: string[];

  // Reviews
  reviewsStats: {
    workEnvironment: number;
    salary: number;
    career: number;
    management: number;
    culture: number;
  };

  // Images
  galleryImages: string[];

  // Contact
  address: string;
  phone: string;
  email: string;
  employees: string[];
}

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Tech Innovations Vietnam',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Leading software development and digital transformation company in Vietnam',
    industry: ['Technology', 'Software Development'],
    location: 'Hồ Chí Minh',
    latitude: 10.8231,
    longitude: 106.6797,
    size: 'large',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '2015-03-20',
    website: 'https://techinnovations.com',
    rating: 4.8,
    totalReviews: 245,
    views: 15420,
    followersCount: 3250,
    tags: ['Technology', 'Software Development', 'Cloud Solutions', 'AI', 'Innovation'],
    aboutCompany:
      'Tech Innovations Vietnam is a leading software development company specializing in cloud solutions, AI, and digital transformation. We partner with global Fortune 500 companies to deliver cutting-edge technology solutions.',
    mission: 'Empowering businesses through innovative technology solutions',
    vision: 'To become the most trusted technology partner in Southeast Asia',
    companyHistory: [
      { year: '2015', milestone: 'Công ty thành lập tại TP. Hồ Chí Minh với 5 nhân viên' },
      { year: '2016', milestone: 'Kỷ niệm 1 năm, mở rộng đội ngũ lên 20 nhân viên' },
      { year: '2017', milestone: 'Ký kết hợp đồng với công ty Fortune 500' },
      { year: '2018', milestone: 'Xây dựng trung tâm công nghệ AI, tuyển dụng 50 nhân viên' },
      { year: '2019', milestone: 'Mở chi nhánh tại Hà Nội, nhân viên tăng lên 100 người' },
      { year: '2020', milestone: 'Ra mắt nền tảng cloud solutions, tăng trưởng 150%' },
      { year: '2021', milestone: 'Hợp tác quốc tế, mở rộng thị trường Đông Nam Á' },
      { year: '2022', milestone: 'Nhân viên tăng lên 200, công ty nhận giải thưởng tốt nhất' },
      { year: '2023', milestone: 'Mở chi nhánh tại Singapore, dự kiến tuyển 100 nhân viên' },
      { year: '2024', milestone: 'Đạt mốc 500 nhân viên, trở thành công ty tech hàng đầu' },
    ],
    openPositions: 12,
    jobCategories: ['Full Stack Developer', 'DevOps Engineer', 'UI/UX Designer', 'Data Scientist'],
    salaryRange: [12, 35],
    salaryByRole: [
      { role: 'Junior Developer', min: 12, max: 18 },
      { role: 'Senior Developer', min: 20, max: 35 },
      { role: 'Tech Lead', min: 28, max: 40 },
    ],
    benefits: ['Health Insurance', 'Gym Membership', 'Free Meals', 'Flexible Hours'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'Paid overtime, max 10 hours/week',
    vacationDays: 15,
    insurances: ['Health Insurance', 'Life Insurance', 'Accident Insurance'],
    salaryBenefits: ['13th Month Salary', 'Performance Bonus', 'Profit Sharing'],
    allowances: ['Meal Allowance: 100k', 'Transportation: 200k', 'Phone: 50k'],
    reviewsStats: {
      workEnvironment: 4.7,
      salary: 4.5,
      career: 4.8,
      management: 4.6,
      culture: 4.9,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
      'https://images.unsplash.com/photo-1552994406-5b4afb005b25?w=500&h=400&fit=crop',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Tầng 15, tòa nhà Bitexco, 2 Hải Triều, Quận 1, TP HCM',
    phone: '+84 28 3827 9999',
    email: 'careers@techinnovations.com',
    employees: ['Nguyễn Văn A', 'Trần Thị B', 'Phạm Văn C'],
  },
  {
    id: '2',
    name: 'FinTech Solutions Asia',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=400&fit=crop',
    description: 'Revolutionary fintech platform transforming digital payments',
    industry: ['Finance', 'Technology'],
    location: 'Hà Nội',
    latitude: 21.0285,
    longitude: 105.8542,
    size: 'medium',
    culture: 'innovative',
    businessType: 'finance',
    employmentType: ['full-time'],
    foundedDate: '2018-06-15',
    website: 'https://fintech-solutions.com',
    rating: 4.6,
    totalReviews: 189,
    views: 12340,
    followersCount: 2100,
    tags: ['Finance', 'FinTech', 'Technology', 'Digital Payments'],
    aboutCompany:
      'FinTech Solutions Asia is disrupting the financial services industry with AI-powered solutions. Our platform serves millions of transactions daily.',
    mission: 'Making financial services accessible to everyone',
    vision: 'The most trusted fintech platform in Asia',
    companyHistory: [
      { year: '2018', milestone: 'FinTech Solutions Asia được thành lập' },
      { year: '2019', milestone: 'Phát triển platform thanh toán di động đầu tiên' },
      { year: '2020', milestone: 'Đạt 1 triệu người dùng, tăng vốn Series A' },
      { year: '2021', milestone: 'Mở rộng sang 3 quốc gia Đông Nam Á' },
      { year: '2022', milestone: 'Tích hợp AI vào hệ thống, xử lý giao dịch tăng 300%' },
      { year: '2023', milestone: 'Đạt 10 triệu người dùng, nhân viên 150 người' },
      { year: '2024', milestone: 'Trở thành fintech unicorn của Đông Nam Á' },
    ],
    openPositions: 8,
    jobCategories: ['Backend Engineer', 'Security Specialist', 'Product Manager'],
    salaryRange: [14, 38],
    salaryByRole: [
      { role: 'Junior Developer', min: 14, max: 20 },
      { role: 'Senior Developer', min: 22, max: 38 },
    ],
    benefits: ['Stock Options', 'Health Insurance', 'Remote Work', 'Learning Budget'],
    workingHours: '8:30 AM - 5:30 PM',
    offDays: 2,
    overTimePolicy: 'Flexible, paid when necessary',
    vacationDays: 18,
    insurances: ['Comprehensive Health Insurance', 'Life Insurance'],
    salaryBenefits: ['13th Month + Bonus', 'Performance-based Incentives'],
    allowances: ['Transportation: 250k', 'Meal: 150k', 'Communication: 100k'],
    reviewsStats: {
      workEnvironment: 4.5,
      salary: 4.7,
      career: 4.6,
      management: 4.4,
      culture: 4.5,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=400&fit=crop',
      'https://images.unsplash.com/photo-1460925895917-aaf4b91c7670?w=500&h=400&fit=crop',
    ],
    address: 'Tầng 10, tòa nhà V-Center, 01 Phan Bội Châu, Hoàn Kiếm, Hà Nội',
    phone: '+84 24 6683 9999',
    email: 'careers@fintech-solutions.com',
    employees: ['Đỗ Văn D', 'Lê Thị E'],
  },
  {
    id: '3',
    name: 'Digital Marketing Hub Vietnam',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-aaf4b91c7670?w=1200&h=400&fit=crop',
    description: 'Premier digital marketing agency for Southeast Asian brands',
    industry: ['Marketing', 'Advertising'],
    location: 'Hồ Chí Minh',
    latitude: 10.8245,
    longitude: 106.692,
    size: 'small',
    culture: 'supportive',
    businessType: 'service',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2017-01-10',
    website: 'https://digitalhub.vn',
    rating: 4.4,
    totalReviews: 156,
    views: 8920,
    followersCount: 1850,
    tags: ['Digital Marketing', 'Marketing', 'Advertising', 'Creative'],
    aboutCompany:
      'We are Vietnam\'s leading digital marketing agency, helping 500+ brands achieve their goals through data-driven strategies.',
    mission: 'Empowering brands through digital excellence',
    vision: 'Leading digital transformation in Southeast Asia',
    companyHistory: [
      { year: '2017', milestone: 'Digital Marketing Hub Vietnam ra đời' },
      { year: '2018', milestone: 'Hỗ trợ 50 thương hiệu, trở nên nổi tiếng' },
      { year: '2019', milestone: 'Mở chi nhánh tại Bangkok, Thailand' },
      { year: '2020', milestone: 'Tuyên bố là hãng quản lý tiếp thị số 1 Việt Nam' },
      { year: '2021', milestone: 'Đạt 500+ khách hàng' },
      { year: '2022', milestone: 'Mở chi nhánh tại Manila, Philippines' },
      { year: '2024', milestone: 'Đạt 1000+ khách hàng trên Đông Nam Á' },
    ],
    openPositions: 5,
    jobCategories: ['Marketing Manager', 'Content Creator', 'SEO Specialist'],
    salaryRange: [10, 25],
    salaryByRole: [
      { role: 'Content Creator', min: 10, max: 15 },
      { role: 'Marketing Manager', min: 15, max: 25 },
    ],
    benefits: ['Flexible Hours', 'Free Coffee', 'Creative Freedom', 'Team Outings'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'Minimal overtime, paid when required',
    vacationDays: 12,
    insurances: ['Health Insurance', 'Accident Insurance'],
    salaryBenefits: ['13th Month', 'Performance Bonus'],
    allowances: ['Meal: 80k', 'Transportation: 150k'],
    reviewsStats: {
      workEnvironment: 4.3,
      salary: 4.2,
      career: 4.4,
      management: 4.5,
      culture: 4.6,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1460925895917-aaf4b91c7670?w=500&h=400&fit=crop',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 3000 0000',
    email: 'careers@digitalhub.vn',
    employees: ['Võ Văn F', 'Bùi Thị G'],
  },
  {
    id: '4',
    name: 'E-commerce Giants Corp',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Vietnam\'s largest online shopping platform',
    industry: ['E-commerce', 'Retail'],
    location: 'Hồ Chí Minh',
    latitude: 10.819,
    longitude: 106.705,
    size: 'enterprise',
    culture: 'corporate',
    businessType: 'retail',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2012-05-20',
    website: 'https://ecommerce-giants.com',
    rating: 4.2,
    totalReviews: 312,
    views: 25600,
    followersCount: 8500,
    tags: ['E-commerce', 'Retail', 'Online Shopping'],
    aboutCompany:
      'With over 10 million monthly active users, we\'re reshaping retail in Vietnam and Southeast Asia.',
    mission: 'Making shopping convenient and affordable',
    vision: 'The most trusted e-commerce platform in Asia',
    companyHistory: [
      { year: '2012', milestone: 'E-commerce Giants Corp được thành lập' },
      { year: '2013', milestone: 'Đạt 100,000 người dùng' },
      { year: '2014', milestone: 'Mở rộng sang các tỉnh thành' },
      { year: '2016', milestone: 'Hợp tác với các thương hiệu lớn' },
      { year: '2018', milestone: 'Đạt 5 triệu người dùng' },
      { year: '2020', milestone: 'Mở rộng sang Campuchia và Lào' },
      { year: '2022', milestone: 'Đạt 10 triệu người dùng hàng tháng' },
    ],
    openPositions: 20,
    jobCategories: ['Product Manager', 'Data Analyst', 'Operations Manager'],
    salaryRange: [13, 32],
    salaryByRole: [
      { role: 'Analyst', min: 13, max: 18 },
      { role: 'Senior Manager', min: 22, max: 32 },
    ],
    benefits: ['Discount on Products', 'Health Insurance', 'Retirement Plan'],
    workingHours: '8:30 AM - 5:30 PM',
    offDays: 2,
    overTimePolicy: 'Limited overtime, paid extra',
    vacationDays: 14,
    insurances: ['Comprehensive Insurance', 'Disability Insurance'],
    salaryBenefits: ['13th Month', 'Annual Bonus'],
    allowances: ['Various allowances based on role'],
    reviewsStats: {
      workEnvironment: 4.1,
      salary: 4.3,
      career: 4.2,
      management: 4.0,
      culture: 4.2,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 7000 7000',
    email: 'careers@ecommerce-giants.com',
    employees: ['Nguyễn H', 'Trần I', 'Phạm J'],
  },
  {
    id: '5',
    name: 'Cloud Infrastructure Pro',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Enterprise cloud infrastructure and managed services',
    industry: ['Cloud Computing', 'Technology'],
    location: 'Hà Nội',
    latitude: 21.0305,
    longitude: 105.8445,
    size: 'medium',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '2016-09-12',
    website: 'https://cloudpro.com',
    rating: 4.7,
    totalReviews: 178,
    views: 11200,
    followersCount: 2800,
    tags: ['Cloud Computing', 'Technology', 'Infrastructure'],
    aboutCompany:
      'Providing enterprise-grade cloud infrastructure with 99.99% uptime guarantee to businesses across Asia.',
    mission: 'Democratizing cloud technology',
    vision: 'Leading cloud provider in Asia',
    companyHistory: [
      { year: '2016', milestone: 'Cloud Infrastructure Pro được thành lập' },
      { year: '2017', milestone: 'Ra mắt dịch vụ cloud đầu tiên' },
      { year: '2018', milestone: 'Đạt 99.99% uptime' },
      { year: '2019', milestone: 'Mở rộng sang 3 quốc gia' },
      { year: '2021', milestone: 'Tăng vốn Series B' },
      { year: '2023', milestone: 'Đạt 500+ khách hàng enterprise' },
    ],
    openPositions: 15,
    jobCategories: ['Cloud Architect', 'SysAdmin', 'Network Engineer'],
    salaryRange: [16, 40],
    salaryByRole: [
      { role: 'Junior SysAdmin', min: 16, max: 22 },
      { role: 'Senior Architect', min: 30, max: 40 },
    ],
    benefits: ['Certification Support', 'Home Office Setup', 'Conference Travel'],
    workingHours: '8:00 AM - 5:00 PM',
    offDays: 2,
    overTimePolicy: 'On-call premium paid',
    vacationDays: 20,
    insurances: ['Comprehensive Health', 'Life Insurance', 'Disability Coverage'],
    salaryBenefits: ['13th Month', 'Quarterly Bonus', 'Stock Options'],
    allowances: ['Transportation: 200k', 'Meal: 120k', 'Equipment: Budget available'],
    reviewsStats: {
      workEnvironment: 4.8,
      salary: 4.6,
      career: 4.7,
      management: 4.7,
      culture: 4.7,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Tầng 8, Quận Ba Đình, Hà Nội',
    phone: '+84 24 6280 0000',
    email: 'careers@cloudpro.com',
    employees: ['Đỗ K', 'Lê L', 'Võ M'],
  },
  {
    id: '6',
    name: 'Design Studio Creativity',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Award-winning creative design studio',
    industry: ['Design', 'Creative'],
    location: 'Hồ Chí Minh',
    latitude: 10.834,
    longitude: 106.665,
    size: 'small',
    culture: 'innovative',
    businessType: 'service',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2014-02-28',
    website: 'https://designcreativity.com',
    rating: 4.5,
    totalReviews: 120,
    views: 7800,
    followersCount: 1600,
    tags: ['Design', 'Creative', 'UI/UX', 'Branding'],
    aboutCompany:
      'Multi-awarded creative design studio specializing in branding, UI/UX, and digital experiences for startups and enterprises.',
    mission: 'Creating meaningful visual experiences',
    vision: 'The most innovative design studio in Vietnam',
    companyHistory: [
      { year: '2014', milestone: 'Design Studio Creativity được thành lập' },
      { year: '2015', milestone: 'Giành giải thiết kế lần thứ nhất' },
      { year: '2017', milestone: 'Đạt 50+ dự án lớn' },
      { year: '2019', milestone: 'Nhận giải thưởng thiết kế quốc tế' },
      { year: '2021', milestone: 'Mở rộng đội ngũ lên 15 người' },
      { year: '2023', milestone: 'Trở thành studio hàng đầu Việt Nam' },
    ],
    openPositions: 4,
    jobCategories: ['UI/UX Designer', 'Graphic Designer', 'Motion Designer'],
    salaryRange: [11, 26],
    salaryByRole: [
      { role: 'Junior Designer', min: 11, max: 15 },
      { role: 'Senior Designer', min: 18, max: 26 },
    ],
    benefits: ['Creative Freedom', 'Design Tools Budget', 'Portfolio Building'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'Flexible, project-based',
    vacationDays: 13,
    insurances: ['Health Insurance', 'Accident Insurance'],
    salaryBenefits: ['13th Month', 'Performance Bonus'],
    allowances: ['Meal: 100k', 'Transportation: 150k'],
    reviewsStats: {
      workEnvironment: 4.6,
      salary: 4.3,
      career: 4.5,
      management: 4.6,
      culture: 4.7,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Quận Phú Nhuận, TP HCM',
    phone: '+84 28 3999 9999',
    email: 'careers@designcreativity.com',
    employees: ['Nguyễn N', 'Trần O'],
  },
  {
    id: '7',
    name: 'Hủ Tiếu Nam Vang Mekong',
    logo: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&h=400&fit=crop',
    description: 'Quán hủ tiếu truyền thống nổi tiếng, tuyển nhân viên phục vụ và đầu bếp',
    industry: ['Food & Beverage'],
    location: 'Hồ Chí Minh',
    latitude: 10.81,
    longitude: 106.712,
    size: 'small',
    culture: 'supportive',
    businessType: 'food',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2010-05-15',
    website: 'https://hutieumekong.com',
    rating: 4.3,
    totalReviews: 87,
    views: 5600,
    followersCount: 890,
    tags: ['Food & Beverage', 'Restaurant', 'Vietnamese Cuisine'],
    aboutCompany:
      'Quán hủ tiếu gia truyền với công thức nước dùng độc quyền. Chúng tôi tìm kiếm những nhân viên nhiệt tình để phục vụ khách hàng.',
    mission: 'Phục vụ những bát hủ tiếu ngon với chất lượng tốt nhất',
    vision: 'Trở thành quán hủ tiếu hàng đầu tại TP HCM',
    companyHistory: [
      { year: '2010', milestone: 'Hủ Tiếu Nam Vang Mekong được thành lập' },
      { year: '2012', milestone: 'Công thức nước dùng độc quyền được phát triển' },
      { year: '2015', milestone: 'Mở rộng sang nhiều địa điểm' },
      { year: '2018', milestone: 'Trở thành quán hủ tiếu nổi tiếng tại TP HCM' },
      { year: '2022', milestone: 'Nhân viên tăng lên 30 người' },
    ],
    openPositions: 3,
    jobCategories: ['Phục vụ bàn', 'Đầu bếp', 'Thu ngân'],
    salaryRange: [4, 8],
    salaryByRole: [
      { role: 'Phục vụ bàn', min: 4, max: 6 },
      { role: 'Đầu bếp', min: 6, max: 8 },
    ],
    benefits: ['Ăn cơm trưa miễn phí', 'Môi trường làm việc tươi vui'],
    workingHours: '6:00 AM - 10:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 8,
    insurances: ['Bảo hiểm xã hội'],
    salaryBenefits: ['Thưởng Tết'],
    allowances: [],
    reviewsStats: {
      workEnvironment: 4.2,
      salary: 4.1,
      career: 4.0,
      management: 4.3,
      culture: 4.4,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 1234 5678',
    email: 'tuyen@hutieumekong.com',
    employees: ['Ngô Văn P', 'Lý Thị Q'],
  },
  {
    id: '8',
    name: 'Trà Sữa Ong Vàng',
    logo: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=1200&h=400&fit=crop',
    description: 'Chuỗi cửa hàng trà sữa hiện đại, tuyển dụng toàn thời gian và bán thời gian',
    industry: ['Food & Beverage', 'Retail'],
    location: 'Hà Nội',
    latitude: 21.0265,
    longitude: 105.865,
    size: 'medium',
    culture: 'innovative',
    businessType: 'food',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2018-03-20',
    website: 'https://trasua-ongvang.vn',
    rating: 4.4,
    totalReviews: 142,
    views: 8900,
    followersCount: 2340,
    tags: ['Food & Beverage', 'Beverage', 'Cafe', 'Tea'],
    aboutCompany:
      'Chuỗi cửa hàng trà sữa với tài nguyên thiên nhiên từ những vùng cao. Tuyển dụng nhân viên bán hàng, pha chế và quản lý cửa hàng.',
    mission: 'Cung cấp trà sữa chất lượng cao với nguyên liệu tự nhiên',
    vision: 'Mở rộng mạng lưới cửa hàng trà sữa trên toàn quốc',
    companyHistory: [
      { year: '2018', milestone: 'Trà Sữa Ong Vàng được thành lập' },
      { year: '2019', milestone: 'Mở cửa hàng thứ 5' },
      { year: '2020', milestone: 'Mở rộng sang Hà Nội' },
      { year: '2022', milestone: 'Đạt 20 cửa hàng trên toàn quốc' },
      { year: '2024', milestone: 'Nhân viên tăng lên 100 người' },
    ],
    openPositions: 6,
    jobCategories: ['Pha chế trà sữa', 'Bán hàng', 'Quản lý ca'],
    salaryRange: [5, 12],
    salaryByRole: [
      { role: 'Nhân viên pha chế', min: 5, max: 7 },
      { role: 'Quản lý ca', min: 8, max: 12 },
    ],
    benefits: ['Đồng phục miễn phí', 'Nước uống miễn phí', 'Cơ hội thăng tiến nhanh'],
    workingHours: '7:00 AM - 10:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 10,
    insurances: ['Bảo hiểm xã hội'],
    salaryBenefits: ['Thưởng tháng'],
    allowances: ['Hỗ trợ xe buýt'],
    reviewsStats: {
      workEnvironment: 4.4,
      salary: 4.2,
      career: 4.3,
      management: 4.4,
      culture: 4.5,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&h=400&fit=crop',
    ],
    address: 'Quận Ba Đình, Hà Nội',
    phone: '+84 24 6789 1234',
    email: 'recruitment@trasua-ongvang.vn',
    employees: ['Hoàng Văn R', 'Hồ Thị S'],
  },
  {
    id: '9',
    name: 'Fashion Hub Việt',
    logo: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=1200&h=400&fit=crop',
    description: 'Cửa hàng thời trang, bán quần áo, phụ kiện - tuyển nhân viên bán hàng',
    industry: ['Retail', 'Fashion'],
    location: 'Hồ Chí Minh',
    latitude: 10.84,
    longitude: 106.655,
    size: 'small',
    culture: 'supportive',
    businessType: 'fashion',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2015-08-10',
    website: 'https://fashionhubviet.com',
    rating: 4.5,
    totalReviews: 98,
    views: 7200,
    followersCount: 1560,
    tags: ['Fashion', 'Retail', 'E-commerce'],
    aboutCompany:
      'Cửa hàng thời trang với các sản phẩm chất lượng từ các nhà thiết kế Việt và quốc tế. Tuyển nhân viên bán hàng, stylist và nhân viên kho.',
    mission: 'Mang thời trang chất lượng đến mọi người',
    vision: 'Trở thành thương hiệu thời trang hàng đầu',
    companyHistory: [
      { year: '2015', milestone: 'Fashion Hub Việt được thành lập' },
      { year: '2017', milestone: 'Hợp tác với các nhà thiết kế Việt' },
      { year: '2019', milestone: 'Mở rộng sang các thành phố khác' },
      { year: '2021', milestone: 'Đạt 5 cửa hàng' },
      { year: '2023', milestone: 'Trở thành thương hiệu thời trang nổi tiếng' },
    ],
    openPositions: 4,
    jobCategories: ['Nhân viên bán hàng', 'Stylist', 'Nhân viên kho'],
    salaryRange: [6, 10],
    salaryByRole: [
      { role: 'Nhân viên bán hàng', min: 6, max: 8 },
      { role: 'Stylist', min: 8, max: 10 },
    ],
    benefits: ['Chiết khấu sản phẩm', 'Đồng phục miễn phí', 'Thưởng hoa hồng'],
    workingHours: '9:00 AM - 9:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm, được thanh toán',
    vacationDays: 9,
    insurances: ['Bảo hiểm xã hội'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng doanh số'],
    allowances: ['Hỗ trợ ăn trưa'],
    reviewsStats: {
      workEnvironment: 4.5,
      salary: 4.3,
      career: 4.4,
      management: 4.5,
      culture: 4.6,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 5555 6666',
    email: 'jobs@fashionhubviet.com',
    employees: ['Phan Văn T', 'Đặng Thị U'],
  },
  {
    id: '10',
    name: 'Cơm Tấm Sài Gòn',
    logo: 'https://images.unsplash.com/photo-1555939594-58d7cb561549?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561549?w=1200&h=400&fit=crop',
    description: 'Chuỗi cơm tấm nổi tiếng tuyên nhân viên phục vụ, nấu ăn part-time',
    industry: ['Food & Beverage', 'Restaurant'],
    location: 'Hồ Chí Minh',
    latitude: 10.815,
    longitude: 106.68,
    size: 'small',
    culture: 'supportive',
    businessType: 'food',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2010-01-15',
    website: 'https://comtamsaigon.vn',
    rating: 4.3,
    totalReviews: 156,
    views: 9800,
    followersCount: 2100,
    tags: ['Food & Beverage', 'Restaurant', 'Traditional'],
    aboutCompany:
      'Chuỗi cơm tấm truyền thống Sài Gòn với 15 chi nhánh trên thành phố. Chúng tôi tuyển nhân viên phục vụ, giúp việc bếp và nhân viên quản lý.',
    mission: 'Phục vụ cơm tấm chất lượng với giá cả bình dân',
    vision: 'Trở thành chuỗi cơm tấm lớn nhất TP HCM',
    companyHistory: [
      { year: '2010', milestone: 'Cơm Tấm Sài Gòn được thành lập' },
      { year: '2012', milestone: 'Mở cửa hàng thứ 2' },
      { year: '2015', milestone: 'Đạt 5 chi nhánh' },
      { year: '2018', milestone: 'Đạt 10 chi nhánh trên TP HCM' },
      { year: '2021', milestone: 'Mở rộng sang Bình Dương' },
      { year: '2024', milestone: 'Đạt 15 chi nhánh, nhân viên 200 người' },
    ],
    openPositions: 8,
    jobCategories: ['Phục vụ bàn', 'Giúp việc bếp', 'Thu ngân', 'Quản lý ca'],
    salaryRange: [5, 9],
    salaryByRole: [
      { role: 'Phục vụ bàn', min: 5, max: 7 },
      { role: 'Giúp việc bếp', min: 6, max: 8 },
      { role: 'Thu ngân', min: 6, max: 8 },
    ],
    benefits: ['Cơm ăn miễn phí', 'Thưởng hoa hồng', 'Đồng phục'],
    workingHours: '10:00 AM - 8:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 8,
    insurances: ['Bảo hiểm xã hội'],
    salaryBenefits: ['Thưởng Tết'],
    allowances: ['Cơm ăn', 'Nước uống'],
    reviewsStats: {
      workEnvironment: 4.2,
      salary: 4.0,
      career: 4.1,
      management: 4.3,
      culture: 4.4,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561549?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 6666 7777',
    email: 'jobs@comtamsaigon.vn',
    employees: ['Nguyễn Văn A', 'Trần Thị B'],
  },
  {
    id: '11',
    name: 'Quán Cafe Sáng Tạo',
    logo: 'https://images.unsplash.com/photo-1495474472456-4d71bcdd2085?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1495474472456-4d71bcdd2085?w=1200&h=400&fit=crop',
    description: 'Quán cafe hiện đại tuyển barista, pha chế, phục vụ part-time',
    industry: ['Food & Beverage', 'Cafe'],
    location: 'Hà Nội',
    latitude: 21.032,
    longitude: 105.84,
    size: 'small',
    culture: 'innovative',
    businessType: 'food',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2018-05-20',
    website: 'https://cafesangtao.vn',
    rating: 4.6,
    totalReviews: 132,
    views: 8500,
    tags: ['Food & Beverage', 'Cafe', 'Beverage'],
    aboutCompany:
      'Quán cafe hiện đại với không gian sáng tạo, tuyên barista, pha chế và nhân viên phục vụ bao gồm cả vị trí part-time.',
    mission: 'Tạo không gian café tuyệt vời cho sinh viên và dân văn phòng',
    vision: 'Mở rộng chuỗi cafe sáng tạo trên khắp Hà Nội',
    companyHistory: [
      { year: '2018', milestone: 'Quán Cafe Sáng Tạo được thành lập' },
      { year: '2019', milestone: 'Trở thành quán cafe nổi tiếng ở Hà Nội' },
      { year: '2020', milestone: 'Mở cửa hàng thứ 2' },
      { year: '2022', milestone: 'Đạt 3 cửa hàng' },
      { year: '2024', milestone: 'Mở rộng sang Đà Nẵng' },
    ],
    openPositions: 6,
    jobCategories: ['Barista', 'Pha chế', 'Phục vụ bàn', 'Quản lý ca'],
    salaryRange: [5, 11],
    salaryByRole: [
      { role: 'Barista', min: 7, max: 11 },
      { role: 'Pha chế', min: 6, max: 10 },
      { role: 'Phục vụ bàn', min: 5, max: 8 },
    ],
    benefits: ['Cà phê miễn phí', 'Thưởng hoa hồng', 'Đồng phục'],
    workingHours: '8:00 AM - 9:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 9,
    insurances: ['Bảo hiểm xã hội'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất'],
    allowances: ['Nước uống', 'Hỗ trợ ăn sáng'],
    reviewsStats: {
      workEnvironment: 4.7,
      salary: 4.4,
      career: 4.5,
      management: 4.6,
      culture: 4.8,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1495474472456-4d71bcdd2085?w=500&h=400&fit=crop',
    ],
    address: 'Quận Ba Đình, Hà Nội',
    phone: '+84 24 7777 8888',
    email: 'jobs@cafesangtao.vn',
    employees: ['Lê Văn C', 'Phạm Thị D'],
  },
  {
    id: '12',
    name: 'Công ty Logistic Express',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad4a1ff6e1ba?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1586528116311-ad4a1ff6e1ba?w=1200&h=400&fit=crop',
    description: 'Công ty logistics tuyển shipper, kho thàng, part-time với lương cao',
    industry: ['Logistics', 'Delivery'],
    location: 'Hồ Chí Minh',
    latitude: 10.828,
    longitude: 106.7,
    size: 'medium',
    culture: 'corporate',
    businessType: 'service',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2016-11-03',
    website: 'https://logisticexpress.vn',
    rating: 4.4,
    totalReviews: 178,
    views: 11200,
    tags: ['Logistics', 'Delivery', 'Service'],
    aboutCompany:
      'Công ty logistics hàng đầu cung cấp dịch vụ giao hàng nhanh, tuyên shipper part-time và nhân viên kho.',
    mission: 'Giao hàng nhanh, an toàn, hiệu quả',
    vision: 'Trở thành công ty logistics số 1 tại Việt Nam',
    companyHistory: [
      { year: '2016', milestone: 'Công ty Logistic Express được thành lập' },
      { year: '2017', milestone: 'Mở rộng dịch vụ giao hàng' },
      { year: '2019', milestone: 'Đạt 1000 shipper' },
      { year: '2021', milestone: 'Mở rộng sang các tỉnh thành' },
      { year: '2023', milestone: 'Đạt 5000 shipper, nhân viên 300 người' },
    ],
    openPositions: 15,
    jobCategories: ['Shipper', 'Nhân viên kho', 'Nhân viên quản lý kho', 'Driver'],
    salaryRange: [6, 15],
    salaryByRole: [
      { role: 'Shipper', min: 6, max: 12 },
      { role: 'Nhân viên kho', min: 7, max: 11 },
      { role: 'Driver', min: 10, max: 15 },
    ],
    benefits: ['Hoa hồng giao hàng', 'Bảo hiểm tai nạn', 'Xe máy hỗ trợ'],
    workingHours: '7:00 AM - 6:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm 150%',
    vacationDays: 10,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm tai nạn'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng doanh số'],
    allowances: ['Hỗ trợ xăng', 'Cơm trưa'],
    reviewsStats: {
      workEnvironment: 4.3,
      salary: 4.5,
      career: 4.2,
      management: 4.4,
      culture: 4.3,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1586528116311-ad4a1ff6e1ba?w=500&h=400&fit=crop',
    ],
    address: 'Quận Tân Bình, TP HCM',
    phone: '+84 28 8888 9999',
    email: 'jobs@logisticexpress.vn',
    employees: ['Hoàng Văn E', 'Võ Thị F'],
  },
  {
    id: '13',
    name: 'Supermarket ABC Chain',
    logo: 'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=1200&h=400&fit=crop',
    description: 'Siêu thị lớn tuyên nhân viên bán hàng, thu ngân, kho part-time',
    industry: ['Retail', 'Supermarket'],
    location: 'Hồ Chí Minh',
    latitude: 10.822,
    longitude: 106.69,
    size: 'large',
    culture: 'corporate',
    businessType: 'retail',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2012-07-18',
    website: 'https://abcchain.vn',
    rating: 4.5,
    totalReviews: 243,
    views: 14500,
    tags: ['Retail', 'Supermarket', 'E-commerce'],
    aboutCompany:
      'Chuỗi siêu thị lớn nhất Việt Nam với 45 chi nhánh, tuyên hàng trăm nhân viên bán hàng, thu ngân và nhân viên kho.',
    mission: 'Cung cấp sản phẩm chất lượng với giá tốt nhất',
    vision: 'Trở thành siêu thị lớn nhất khu vực Đông Nam Á',
    companyHistory: [
      { year: '2012', milestone: 'Supermarket ABC Chain được thành lập' },
      { year: '2014', milestone: 'Mở cửa hàng thứ 10' },
      { year: '2016', milestone: 'Đạt 20 chi nhánh' },
      { year: '2019', milestone: 'Đạt 35 chi nhánh, mở rộng sang Campuchia' },
      { year: '2023', milestone: 'Đạt 45 chi nhánh, nhân viên 2000 người' },
    ],
    openPositions: 25,
    jobCategories: ['Nhân viên bán hàng', 'Thu ngân', 'Nhân viên kho', 'Quản lý ca'],
    salaryRange: [5, 12],
    salaryByRole: [
      { role: 'Nhân viên bán hàng', min: 5, max: 8 },
      { role: 'Thu ngân', min: 6, max: 9 },
      { role: 'Nhân viên kho', min: 6, max: 10 },
    ],
    benefits: ['Chiết khấu sản phẩm 20%', 'Đồng phục', 'Thưởng hoa hồng'],
    workingHours: '8:00 AM - 9:00 PM',
    offDays: 2,
    overTimePolicy: 'Tính công thêm 150%',
    vacationDays: 10,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất'],
    allowances: ['Cơm trưa', 'Hỗ trợ đi lại'],
    reviewsStats: {
      workEnvironment: 4.4,
      salary: 4.3,
      career: 4.2,
      management: 4.5,
      culture: 4.4,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=500&h=400&fit=crop',
    ],
    address: 'Quận 7, TP HCM',
    phone: '+84 28 9999 0000',
    email: 'jobs@abcchain.vn',
    employees: ['Bùi Văn G', 'Trương Thị H'],
  },
  {
    id: '14',
    name: 'Training Academy Vietnam',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Trung tâm đào tạo tuyển giáo viên, trợ lý giảng dạy, thực tập sinh',
    industry: ['Education', 'Training'],
    location: 'Hà Nội',
    latitude: 21.0245,
    longitude: 105.87,
    size: 'medium',
    culture: 'supportive',
    businessType: 'education',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2013-02-28',
    website: 'https://trainingacademyvn.edu',
    rating: 4.7,
    totalReviews: 198,
    views: 12300,
    tags: ['Education', 'Training', 'Learning'],
    aboutCompany:
      'Trung tâm đào tạo hàng đầu tại Hà Nội cung cấp các khóa học lập trình, ngoại ngữ và kỹ năng mềm. Tuyên giáo viên, trợ lý giảng dạy và thực tập sinh.',
    mission: 'Nâng cao chất lượng đào tạo nhân lực Việt Nam',
    vision: 'Trở thành trung tâm đào tạo hàng đầu Đông Nam Á',
    companyHistory: [
      { year: '2013', milestone: 'Training Academy Vietnam được thành lập' },
      { year: '2015', milestone: 'Khai giảng khóa học lập trình đầu tiên' },
      { year: '2017', milestone: 'Đạt 5000 học viên' },
      { year: '2019', milestone: 'Mở chi nhánh tại Bangkok' },
      { year: '2022', milestone: 'Đạt 20000 học viên, tuyên 50 giáo viên' },
    ],
    openPositions: 10,
    jobCategories: ['Giáo viên', 'Trợ lý giảng dạy', 'Thực tập sinh', 'Nhân viên hành chính'],
    salaryRange: [8, 18],
    salaryByRole: [
      { role: 'Giáo viên', min: 12, max: 18 },
      { role: 'Trợ lý giảng dạy', min: 8, max: 12 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Học tập miễn phí', 'Bảo hiểm y tế', 'Thưởng hiệu suất'],
    workingHours: '8:30 AM - 5:30 PM',
    offDays: 2,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 12,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất', 'Lương tháng 13'],
    allowances: ['Cơm trưa', 'Hỗ trợ di chuyển'],
    reviewsStats: {
      workEnvironment: 4.8,
      salary: 4.5,
      career: 4.7,
      management: 4.6,
      culture: 4.8,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Quận Cầu Giấy, Hà Nội',
    phone: '+84 24 1111 2222',
    email: 'jobs@trainingacademyvn.edu',
    employees: ['Tạ Văn I', 'Dương Thị J'],
  },
  {
    id: '15',
    name: 'Digital Marketing Pro',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Công ty marketing số hóa tuyên content creator, social media, thực tập sinh',
    industry: ['Marketing', 'Digital Marketing'],
    location: 'Hồ Chí Minh',
    latitude: 10.835,
    longitude: 106.67,
    size: 'small',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2017-09-12',
    website: 'https://digitalpro.vn',
    rating: 4.6,
    totalReviews: 145,
    views: 9800,
    tags: ['Digital Marketing', 'Content', 'Social Media'],
    aboutCompany:
      'Công ty marketing số hóa chuyên tạo nội dung, quản lý mạng xã hội, chạy quảng cáo Facebook/Google cho các brand. Tuyên content creator, social media manager và thực tập sinh marketing.',
    mission: 'Giúp các doanh nghiệp phát triển trên nền tảng số',
    vision: 'Trở thành agentu digital marketing hàng đầu Việt Nam',
    companyHistory: [
      { year: '2017', milestone: 'Digital Marketing Pro được thành lập' },
      { year: '2018', milestone: 'Hỗ trợ 50 brand' },
      { year: '2019', milestone: 'Mở chi nhánh tại Bình Dương' },
      { year: '2021', milestone: 'Đạt 200 brand khách hàng' },
      { year: '2023', milestone: 'Nhân viên 30 người, doanh thu tăng 300%' },
    ],
    openPositions: 8,
    jobCategories: ['Content Creator', 'Social Media Manager', 'Ads Manager', 'Thực tập sinh'],
    salaryRange: [7, 16],
    salaryByRole: [
      { role: 'Content Creator', min: 10, max: 16 },
      { role: 'Social Media Manager', min: 9, max: 15 },
      { role: 'Ads Manager', min: 10, max: 16 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Học tập công nghệ mới', 'Thưởng doanh số', 'Môi trường sáng tạo'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'Linh hoạt',
    vacationDays: 12,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất'],
    allowances: ['Cơm trưa', 'Nước uống'],
    reviewsStats: {
      workEnvironment: 4.7,
      salary: 4.5,
      career: 4.8,
      management: 4.6,
      culture: 4.9,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop',
    ],
    address: 'Quận 3, TP HCM',
    phone: '+84 28 2222 3333',
    email: 'jobs@digitalpro.vn',
    employees: ['Ngô Văn K', 'Kiều Thị L'],
  },
  {
    id: '16',
    name: 'Thiết Kế Đồ Họa Creative Hub',
    logo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=400&fit=crop',
    description: 'Studio thiết kế đồ họa tuyên designer, UI/UX, motion designer, thực tập sinh',
    industry: ['Design', 'Creative Services'],
    location: 'Hà Nội',
    latitude: 21.034,
    longitude: 105.835,
    size: 'small',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2016-04-05',
    website: 'https://creativehub.vn',
    rating: 4.8,
    totalReviews: 167,
    views: 10500,
    tags: ['Design', 'Creative', 'Graphic Design'],
    aboutCompany:
      'Studio thiết kế đồ họa sáng tạo với đội ngũ designer giàu kinh nghiệm. Tuyên UI/UX Designer, Graphic Designer, Motion Designer và thực tập sinh thiết kế.',
    mission: 'Tạo ra những thiết kế sáng tạo và có tác động',
    vision: 'Trở thành studio thiết kế hàng đầu Việt Nam',
    companyHistory: [
      { year: '2016', milestone: 'Thiết Kế Đồ Họa Creative Hub được thành lập' },
      { year: '2017', milestone: 'Giành giải thiết kế quốc gia' },
      { year: '2018', milestone: 'Đạt 20 dự án lớn' },
      { year: '2020', milestone: 'Nhân viên tăng lên 20 người' },
      { year: '2023', milestone: 'Trở thành studio thiết kế hàng đầu Hà Nội' },
    ],
    openPositions: 7,
    jobCategories: ['UI/UX Designer', 'Graphic Designer', 'Motion Designer', 'Thực tập sinh'],
    salaryRange: [9, 20],
    salaryByRole: [
      { role: 'UI/UX Designer', min: 12, max: 20 },
      { role: 'Graphic Designer', min: 10, max: 18 },
      { role: 'Motion Designer', min: 12, max: 20 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Máy tính cao cấp', 'Phần mềm miễn phí', 'Học tập thiết kế'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'Linh hoạt',
    vacationDays: 12,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất'],
    allowances: ['Cơm trưa', 'Nước uống'],
    reviewsStats: {
      workEnvironment: 4.9,
      salary: 4.6,
      career: 4.8,
      management: 4.7,
      culture: 4.9,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=400&fit=crop',
    ],
    address: 'Quận Hoàn Kiếm, Hà Nội',
    phone: '+84 24 3333 4444',
    email: 'jobs@creativehub.vn',
    employees: ['Đặng Văn M', 'Lý Thị N'],
  },
  {
    id: '17',
    name: 'Công Ty Bảo Hiểm Việt Nhân',
    logo: 'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=1200&h=400&fit=crop',
    description: 'Công ty bảo hiểm tuyên sale, customer service, nhân viên hành chính, thực tập',
    industry: ['Insurance', 'Finance'],
    location: 'Hồ Chí Minh',
    latitude: 10.81,
    longitude: 106.72,
    size: 'large',
    culture: 'corporate',
    businessType: 'finance',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2005-06-10',
    website: 'https://vietnaminsurance.vn',
    rating: 4.5,
    totalReviews: 234,
    views: 13200,
    tags: ['Finance', 'Insurance'],
    aboutCompany:
      'Công ty bảo hiểm lớn với 20 năm kinh nghiệm. Tuyên nhân viên bán hàng, customer service, nhân viên hành chính và thực tập sinh tài chính.',
    mission: 'Bảo vệ tương lai của mọi gia đình Việt',
    vision: 'Trở thành công ty bảo hiểm số 1 Việt Nam',
    companyHistory: [
      { year: '2005', milestone: 'Công Ty Bảo Hiểm Việt Nhân được thành lập' },
      { year: '2008', milestone: 'Mở rộng thị trường bảo hiểm nhân thọ' },
      { year: '2012', milestone: 'Đạt 100,000 khách hàng' },
      { year: '2017', milestone: 'Mở chi nhánh tại 10 tỉnh thành' },
      { year: '2023', milestone: 'Đạt 500,000 khách hàng, nhân viên 500 người' },
    ],
    openPositions: 12,
    jobCategories: ['Sales Representative', 'Customer Service', 'Nhân viên hành chính', 'Thực tập sinh'],
    salaryRange: [8, 18],
    salaryByRole: [
      { role: 'Sales Representative', min: 10, max: 18 },
      { role: 'Customer Service', min: 8, max: 12 },
      { role: 'Nhân viên hành chính', min: 7, max: 11 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Hoa hồng cao', 'Bảo hiểm y tế', 'Đào tạo liên tục'],
    workingHours: '8:30 AM - 5:30 PM',
    offDays: 2,
    overTimePolicy: 'Tính công thêm',
    vacationDays: 12,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế', 'Bảo hiểm thân thể'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất', 'Lương tháng 13'],
    allowances: ['Cơm trưa', 'Hỗ trợ di chuyển'],
    reviewsStats: {
      workEnvironment: 4.4,
      salary: 4.5,
      career: 4.6,
      management: 4.5,
      culture: 4.5,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1552821554-5fefe8c9ef14?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 4444 5555',
    email: 'jobs@vietnaminsurance.vn',
    employees: ['Chử Văn O', 'Mạc Thị P'],
  },
  {
    id: '18',
    name: 'Công Ty Cung Cấp Lao Động',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=400&fit=crop',
    description: 'Công ty cung cấp lao động tuyên nhân viên kho, nhân viên nhà máy, công nhân',
    industry: ['Human Resources', 'Staffing'],
    location: 'Hồ Chí Minh',
    latitude: 10.826,
    longitude: 106.685,
    size: 'medium',
    culture: 'corporate',
    businessType: 'service',
    employmentType: ['full-time', 'part-time'],
    foundedDate: '2011-08-22',
    website: 'https://staffingvietnam.vn',
    rating: 4.3,
    totalReviews: 189,
    views: 11800,
    tags: ['Human Resources', 'Staffing', 'Service'],
    aboutCompany:
      'Công ty cung cấp lao động cạnh tranh với các kỹ năng nhân viên kho, nhân viên nhà máy, công nhân xây dựng.',
    mission: 'Kết nối người lao động với những cơ hội việc làm tốt',
    vision: 'Trở thành công ty cung cấp lao động tin cậy nhất',
    companyHistory: [
      { year: '2011', milestone: 'Công Ty Cung Cấp Lao Động được thành lập' },
      { year: '2013', milestone: 'Đạt 1000 lao động' },
      { year: '2016', milestone: 'Mở rộng sang các tỉnh khác' },
      { year: '2019', milestone: 'Đạt 5000 lao động được cung cấp' },
      { year: '2023', milestone: 'Đạt 10000 lao động, hợp tác với 100 công ty' },
    ],
    openPositions: 20,
    jobCategories: ['Nhân viên kho', 'Công nhân nhà máy', 'Công nhân xây dựng', 'Lao động phổ thông'],
    salaryRange: [5, 12],
    salaryByRole: [
      { role: 'Nhân viên kho', min: 6, max: 10 },
      { role: 'Công nhân nhà máy', min: 7, max: 11 },
      { role: 'Công nhân xây dựng', min: 8, max: 12 },
    ],
    benefits: ['Bảo hiểm đầy đủ', 'Đồng phục', 'Hỗ trợ ăn ở'],
    workingHours: '7:00 AM - 4:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm 150%',
    vacationDays: 9,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm thân thể', 'Bảo hiểm tai nạn lao động'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng năng suất'],
    allowances: ['Cơm trưa', 'Xe đưa đón'],
    reviewsStats: {
      workEnvironment: 4.2,
      salary: 4.3,
      career: 4.1,
      management: 4.3,
      culture: 4.2,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=400&fit=crop',
    ],
    address: 'Quận Tân Phú, TP HCM',
    phone: '+84 28 5555 6666',
    email: 'jobs@staffingvietnam.vn',
    employees: ['Vân Văn Q', 'Sáu Thị R'],
  },
  {
    id: '19',
    name: 'Bệnh Viện Quốc Tế Việt',
    logo: 'https://images.unsplash.com/photo-1631217314830-4e466b59290f?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1631217314830-4e466b59290f?w=1200&h=400&fit=crop',
    description: 'Bệnh viện quốc tế tuyên y tá, nhân viên hành chính, thực tập sinh y tế',
    industry: ['Healthcare', 'Hospital'],
    location: 'Hà Nội',
    latitude: 21.028,
    longitude: 105.86,
    size: 'large',
    culture: 'supportive',
    businessType: 'healthcare',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2008-03-18',
    website: 'https://vietnamhospital.vn',
    rating: 4.7,
    totalReviews: 267,
    views: 15600,
    tags: ['Healthcare', 'Hospital', 'Medical'],
    aboutCompany:
      'Bệnh viện quốc tế hiện đại với trang thiết bị y tế tốt nhất. Tuyên y tá, nhân viên hành chính, nhân viên vệ sinh và thực tập sinh y tế.',
    mission: 'Cung cấp dịch vụ y tế chất lượng cao',
    vision: 'Trở thành bệnh viện hàng đầu Đông Nam Á',
    companyHistory: [
      { year: '2008', milestone: 'Bệnh Viện Quốc Tế Việt được thành lập' },
      { year: '2010', milestone: 'Khai trương khoa phẫu thuật hiện đại' },
      { year: '2014', milestone: 'Mở rộng 5 khoa chuyên khoa' },
      { year: '2018', milestone: 'Nhân viên tăng lên 300 người' },
      { year: '2023', milestone: 'Trở thành bệnh viện quốc tế hàng đầu Việt Nam' },
    ],
    openPositions: 18,
    jobCategories: ['Y tá', 'Nhân viên hành chính', 'Nhân viên vệ sinh', 'Thực tập sinh'],
    salaryRange: [7, 20],
    salaryByRole: [
      { role: 'Y tá', min: 12, max: 20 },
      { role: 'Nhân viên hành chính', min: 8, max: 13 },
      { role: 'Nhân viên vệ sinh', min: 6, max: 9 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Bảo hiểm y tế đầy đủ', 'Đoàn tưởng trợ cấp', 'Học tập chuyên môn'],
    workingHours: '24/7 (Ca)',
    offDays: 2,
    overTimePolicy: 'Tính công thêm 150%',
    vacationDays: 12,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế', 'Bảo hiểm thân thể'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất', 'Lương tháng 13'],
    allowances: ['Cơm trưa', 'Hỗ trợ di chuyển', 'Quần áo làm việc'],
    reviewsStats: {
      workEnvironment: 4.6,
      salary: 4.5,
      career: 4.7,
      management: 4.6,
      culture: 4.7,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1631217314830-4e466b59290f?w=500&h=400&fit=crop',
    ],
    address: 'Quận Ba Đình, Hà Nội',
    phone: '+84 24 6666 7777',
    email: 'jobs@vietnamhospital.vn',
    employees: ['Lâu Văn S', 'Từ Thị T'],
  },
  {
    id: '20',
    name: 'Restaurant & Bar Hải Yến',
    logo: 'https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=1200&h=400&fit=crop',
    description: 'Nhà hàng hải sản sang trọng tuyên phục vụ, bartender, bếp trưởng, thực tập',
    industry: ['Food & Beverage', 'Restaurant'],
    location: 'Hồ Chí Minh',
    latitude: 10.819,
    longitude: 106.708,
    size: 'medium',
    culture: 'corporate',
    businessType: 'food',
    employmentType: ['full-time', 'part-time', 'internship'],
    foundedDate: '2014-10-08',
    website: 'https://restauranthaiyenhotel.vn',
    rating: 4.8,
    totalReviews: 312,
    views: 18900,
    tags: ['Food & Beverage', 'Restaurant', 'Luxury'],
    aboutCompany:
      'Nhà hàng hải sản sang trọng nằm tại trung tâm TP HCM phục vụ các khách hàng quốc tế. Tuyên phục vụ, bartender, bếp trưởng, đầu bếp.',
    mission: 'Mang đến trải nghiệm ẩm thực tuyệt vời',
    vision: 'Trở thành nhà hàng hải sản hàng đầu',
    companyHistory: [
      { year: '2014', milestone: 'Restaurant & Bar Hải Yến được thành lập' },
      { year: '2015', milestone: 'Nhân viên tăng lên 30 người' },
      { year: '2017', milestone: 'Đạt giải nhà hàng tốt nhất TP HCM' },
      { year: '2019', milestone: 'Mở chi nhánh thứ 2' },
      { year: '2023', milestone: 'Trở thành nhà hàng hải sản nổi tiếng quốc tế' },
    ],
    openPositions: 11,
    jobCategories: ['Phục vụ', 'Bartender', 'Bếp trưởng', 'Đầu bếp', 'Thực tập sinh'],
    salaryRange: [8, 22],
    salaryByRole: [
      { role: 'Phục vụ', min: 8, max: 14 },
      { role: 'Bartender', min: 12, max: 22 },
      { role: 'Bếp trưởng', min: 15, max: 22 },
      { role: 'Đầu bếp', min: 10, max: 18 },
      { role: 'Thực tập sinh', min: 4, max: 6 },
    ],
    benefits: ['Ăn uống miễn phí', 'Thưởng hoa hồng cao', 'Đồng phục sang trọng'],
    workingHours: '10:30 AM - 11:00 PM',
    offDays: 1,
    overTimePolicy: 'Tính công thêm 150%, có hoa hồng',
    vacationDays: 10,
    insurances: ['Bảo hiểm xã hội', 'Bảo hiểm y tế'],
    salaryBenefits: ['Thưởng Tết', 'Thưởng hiệu suất', 'Hoa hồng bán hàng'],
    allowances: ['Ăn uống', 'Hỗ trợ di chuyển'],
    reviewsStats: {
      workEnvironment: 4.8,
      salary: 4.6,
      career: 4.7,
      management: 4.8,
      culture: 4.9,
    },
    galleryImages: [
      'https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=500&h=400&fit=crop',
    ],
    address: 'Quận 1, TP HCM',
    phone: '+84 28 7777 8888',
    email: 'jobs@haiyenrestaurant.vn',
    employees: ['Trần Văn U', 'Nguyễn Thị V'],
  },
  {
    id: '21',
    name: 'Viettel IT',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Công ty IT hàng đầu Việt Nam chuyên phát triển phần mềm, hạ tầng CNTT',
    industry: ['Technology', 'Software Development'],
    location: 'Hà Nội',
    latitude: 21.031,
    longitude: 105.848,
    size: 'large',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '2008-01-10',
    website: 'https://viettel-it.vn',
    rating: 4.7,
    totalReviews: 312,
    views: 18900,
    tags: ['Technology', 'Software Development', 'IT Services'],
    aboutCompany: 'Viettel IT là công ty con của Tập đoàn Viettel chuyên cung cấp dịch vụ CNTT, phát triển phần mềm và giải pháp kỹ thuật cho các doanh nghiệp lớn.',
    mission: 'Nâng cao chất lượng dịch vụ CNTT tại Việt Nam',
    vision: 'Trở thành công ty IT hàng đầu Đông Nam Á',
    companyHistory: [
      { year: '2008', milestone: 'Viettel IT được thành lập' },
      { year: '2010', milestone: 'Mở rộng dịch vụ IT services' },
      { year: '2015', milestone: 'Đạt 500 nhân viên' },
      { year: '2019', milestone: 'Mở chi nhánh quốc tế' },
      { year: '2023', milestone: 'Đạt 1000 nhân viên, doanh thu 500 tỷ' },
    ],
    openPositions: 30,
    jobCategories: ['Java Developer', 'Python Developer', 'DevOps Engineer', 'System Admin'],
    salaryRange: [15, 45],
    salaryByRole: [
      { role: 'Junior Developer', min: 15, max: 25 },
      { role: 'Senior Developer', min: 30, max: 45 },
      { role: 'DevOps Engineer', min: 25, max: 40 },
    ],
    benefits: ['Training Fund', 'Health Insurance', 'Stock Options', 'International Travel'],
    workingHours: '8:00 AM - 5:00 PM',
    offDays: 2,
    overTimePolicy: 'OT premium 150%',
    vacationDays: 20,
    insurances: ['Comprehensive Health', 'Life Insurance', 'Disability Coverage'],
    salaryBenefits: ['13th Month Salary', 'Annual Bonus', 'Stock Options'],
    allowances: ['Transportation: 300k', 'Meal: 150k', 'Phone: 200k'],
    reviewsStats: { workEnvironment: 4.7, salary: 4.6, career: 4.8, management: 4.7, culture: 4.7 },
    galleryImages: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop'],
    address: 'Tầng 15, Quận Đống Đa, Hà Nội',
    phone: '+84 24 3333 4444',
    email: 'careers@viettel-it.vn',
    employees: ['Trần Quốc A', 'Hồ Thị B'],
  },
  {
    id: '22',
    name: 'FPT Software',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Công ty phần mềm hàng đầu Việt Nam, cơ sở toàn cầu, chuyên phát triển phần mềm',
    industry: ['Technology', 'Software Development'],
    location: 'Hà Nội',
    latitude: 21.025,
    longitude: 105.875,
    size: 'large',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '1999-12-20',
    website: 'https://fpt-software.com',
    rating: 4.8,
    totalReviews: 425,
    views: 22100,
    tags: ['Technology', 'Software Development', 'Global'],
    aboutCompany: 'FPT Software là công ty phần mềm hàng đầu Việt Nam với các chi nhánh trên toàn thế giới, chuyên phát triển phần mềm cho các tập đoàn lớn.',
    mission: 'Tạo ra những giải pháp phần mềm thay đổi thế giới',
    vision: 'Trở thành công ty phần mềm hàng đầu Châu Á',
    companyHistory: [
      { year: '1999', milestone: 'FPT Software được thành lập' },
      { year: '2005', milestone: 'IPO tại HOSE' },
      { year: '2010', milestone: 'Mở chi nhánh tại Nhật Bản' },
      { year: '2015', milestone: 'Mở chi nhánh tại Mỹ' },
      { year: '2023', milestone: 'Đạt 3000 nhân viên, doanh thu 1.5 tỷ USD' },
    ],
    openPositions: 50,
    jobCategories: ['C++ Developer', 'C# Developer', 'Full Stack Developer', 'QA Engineer'],
    salaryRange: [18, 50],
    salaryByRole: [
      { role: 'Junior Developer', min: 18, max: 28 },
      { role: 'Senior Developer', min: 35, max: 50 },
      { role: 'Tech Lead', min: 40, max: 55 },
    ],
    benefits: ['Annual Bonus', 'Health Insurance', 'Learning Budget', 'Work Flexibility'],
    workingHours: '8:30 AM - 5:30 PM',
    offDays: 2,
    overTimePolicy: 'OT premium 150%',
    vacationDays: 20,
    insurances: ['Comprehensive Health', 'Life Insurance', 'Accident Coverage'],
    salaryBenefits: ['14th Month Salary', 'Performance Bonus', 'Share Options'],
    allowances: ['Transportation: 350k', 'Meal: 200k', 'Phone: 250k'],
    reviewsStats: { workEnvironment: 4.8, salary: 4.7, career: 4.9, management: 4.8, culture: 4.8 },
    galleryImages: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop'],
    address: 'Tầng 20, Quận Thanh Xuân, Hà Nội',
    phone: '+84 24 4444 5555',
    email: 'recruitment@fpt-software.com',
    employees: ['Ngô Văn C', 'Lý Thị D'],
  },
  {
    id: '23',
    name: 'KMS Technology',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Công ty công nghệ chuyên phát triển phần mềm, bao gồm AI, blockchain, cloud',
    industry: ['Technology', 'Software Development'],
    location: 'Hồ Chí Minh',
    latitude: 10.831,
    longitude: 106.66,
    size: 'large',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '2009-06-15',
    website: 'https://kms-technology.com',
    rating: 4.7,
    totalReviews: 298,
    views: 17800,
    tags: ['Technology', 'AI', 'Blockchain', 'Cloud'],
    aboutCompany: 'KMS Technology là công ty công nghệ chuyên cung cấp dịch vụ phát triển phần mềm, AI/ML, blockchain cho các doanh nghiệp trên thế giới.',
    mission: 'Cung cấp giải pháp công nghệ tiên tiến',
    vision: 'Trở thành công ty công nghệ hàng đầu Đông Nam Á',
    companyHistory: [
      { year: '2009', milestone: 'KMS Technology được thành lập' },
      { year: '2012', milestone: 'Chuyên tâm vào AI/ML' },
      { year: '2016', milestone: 'Mở chi nhánh tại Đà Nẵng' },
      { year: '2020', milestone: 'Tăng vốn Series C' },
      { year: '2023', milestone: 'Đạt 800 nhân viên, doanh thu 250 triệu USD' },
    ],
    openPositions: 25,
    jobCategories: ['Machine Learning Engineer', 'Blockchain Developer', 'Cloud Architect', 'Data Scientist'],
    salaryRange: [20, 55],
    salaryByRole: [
      { role: 'ML Engineer', min: 30, max: 50 },
      { role: 'Senior Developer', min: 28, max: 45 },
      { role: 'Data Scientist', min: 25, max: 55 },
    ],
    benefits: ['Stock Options', 'Learning Budget', 'Health Insurance', 'Flexible Hours'],
    workingHours: 'Flexible',
    offDays: 2,
    overTimePolicy: 'Compensation based on project',
    vacationDays: 21,
    insurances: ['Comprehensive Health', 'Life Insurance', 'Disability Coverage'],
    salaryBenefits: ['Annual Bonus', 'Stock Options', 'Performance Bonus'],
    allowances: ['Transportation: 400k', 'Meal: 200k', 'Equipment Budget'],
    reviewsStats: { workEnvironment: 4.8, salary: 4.8, career: 4.9, management: 4.7, culture: 4.9 },
    galleryImages: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop'],
    address: 'Tầng 10, Quận 1, TP HCM',
    phone: '+84 28 5555 6666',
    email: 'careers@kms-technology.com',
    employees: ['Hoàng Văn E', 'Võ Thị F'],
  },
  {
    id: '24',
    name: 'CMCC Tech Solutions',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    description: 'Công ty giải pháp công nghệ chuyên phát triển ứng dụng web, mobile, IoT',
    industry: ['Technology', 'Software Development'],
    location: 'Hà Nội',
    latitude: 21.025,
    longitude: 105.875,
    size: 'medium',
    culture: 'innovative',
    businessType: 'technology',
    employmentType: ['full-time'],
    foundedDate: '2010-03-22',
    website: 'https://cmcc-tech.vn',
    rating: 4.6,
    totalReviews: 156,
    views: 10200,
    tags: ['Technology', 'Software Development', 'Web Development'],
    aboutCompany: 'CMCC Tech Solutions là công ty giải pháp công nghệ chuyên phát triển ứng dụng web, mobile, IoT cho các doanh nghiệp.',
    mission: 'Cung cấp giải pháp công nghệ chất lượng cao',
    vision: 'Trở thành công ty giải pháp công nghệ hàng đầu Việt Nam',
    companyHistory: [
      { year: '2010', milestone: 'CMCC Tech Solutions được thành lập' },
      { year: '2013', milestone: 'Chuyên tâm vào phát triển mobile apps' },
      { year: '2017', milestone: 'Mở rộng dịch vụ cloud' },
      { year: '2021', milestone: 'Đạt 150 nhân viên' },
      { year: '2023', milestone: 'Doanh thu tăng 200%, khách hàng 100+' },
    ],
    openPositions: 15,
    jobCategories: ['React Developer', 'Node.js Developer', 'Mobile Developer', 'DevOps Engineer'],
    salaryRange: [16, 40],
    salaryByRole: [
      { role: 'Junior Developer', min: 16, max: 24 },
      { role: 'Senior Developer', min: 28, max: 40 },
      { role: 'Tech Lead', min: 35, max: 45 },
    ],
    benefits: ['Flexible Work', 'Training Budget', 'Health Insurance', 'Team Building'],
    workingHours: '9:00 AM - 6:00 PM',
    offDays: 2,
    overTimePolicy: 'OT premium 150%',
    vacationDays: 18,
    insurances: ['Health Insurance', 'Accident Coverage'],
    salaryBenefits: ['13th Month', 'Performance Bonus', 'Quarterly Bonus'],
    allowances: ['Transportation: 250k', 'Meal: 150k', 'Phone: 150k'],
    reviewsStats: { workEnvironment: 4.6, salary: 4.5, career: 4.7, management: 4.6, culture: 4.7 },
    galleryImages: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=400&fit=crop'],
    address: 'Tầng 12, Quận Cầu Giấy, Hà Nội',
    phone: '+84 24 6666 7777',
    email: 'jobs@cmcc-tech.vn',
    employees: ['Phan Văn G', 'Đặng Thị H'],
  },
];

