/**
 * Comprehensive IT Skills Database
 * Contains all major programming languages, frameworks, tools, and technologies
 */

export interface SkillCategory {
  name: string;
  skills: string[];
}

export const IT_SKILLS: SkillCategory[] = [
  {
    name: 'Frontend Frameworks & Libraries',
    skills: [
      'React',
      'Vue.js',
      'Angular',
      'Svelte',
      'Next.js',
      'Nuxt.js',
      'Gatsby',
      'Remix',
      'Qwik',
      'Astro',
      'Solid.js',
      'Preact',
    ],
  },
  {
    name: 'Backend Frameworks',
    skills: [
      'Node.js',
      'Express.js',
      'NestJS',
      'Django',
      'Flask',
      'FastAPI',
      'Spring Boot',
      'Spring Framework',
      'Laravel',
      'Ruby on Rails',
      'ASP.NET Core',
      'Go Gin',
      'Fiber',
      'Echo',
      'Deno',
      'Bun',
    ],
  },
  {
    name: 'Programming Languages',
    skills: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'C',
      'Go',
      'Rust',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'Scala',
      'R',
      'MATLAB',
      'Perl',
      'Shell Script',
      'Bash',
      'PowerShell',
    ],
  },
  {
    name: 'Mobile Development',
    skills: [
      'React Native',
      'Flutter',
      'Swift',
      'Kotlin',
      'Xamarin',
      'Ionic',
      'NativeScript',
      'Capacitor',
      'Expo',
      'Android Studio',
      'Xcode',
    ],
  },
  {
    name: 'Databases',
    skills: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'SQLite',
      'Oracle Database',
      'SQL Server',
      'Cassandra',
      'DynamoDB',
      'Firebase',
      'Firestore',
      'Elasticsearch',
      'InfluxDB',
      'Neo4j',
      'MariaDB',
    ],
  },
  {
    name: 'Database Management & ORMs',
    skills: [
      'Prisma',
      'Sequelize',
      'TypeORM',
      'SQLAlchemy',
      'Hibernate',
      'Entity Framework',
      'Mongoose',
      'Drizzle',
      'MikroORM',
    ],
  },
  {
    name: 'Cloud Platforms',
    skills: [
      'AWS',
      'Azure',
      'Google Cloud Platform',
      'Heroku',
      'DigitalOcean',
      'Vercel',
      'Netlify',
      'Firebase',
      'Cloudflare',
      'Linode',
      'IBM Cloud',
      'Oracle Cloud',
    ],
  },
  {
    name: 'DevOps & CI/CD',
    skills: [
      'Docker',
      'Kubernetes',
      'Jenkins',
      'GitLab CI/CD',
      'GitHub Actions',
      'Travis CI',
      'CircleCI',
      'Terraform',
      'Ansible',
      'Puppet',
      'Chef',
      'Nginx',
      'Apache',
      'Linux',
      'Docker Compose',
    ],
  },
  {
    name: 'Version Control & Collaboration',
    skills: [
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
      'SVN',
      'Mercurial',
      'Perforce',
    ],
  },
  {
    name: 'UI/UX & Design Tools',
    skills: [
      'Figma',
      'Adobe XD',
      'Sketch',
      'InVision',
      'Protopie',
      'Framer',
      'Webflow',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Canva',
    ],
  },
  {
    name: 'CSS & Styling',
    skills: [
      'CSS3',
      'Tailwind CSS',
      'Bootstrap',
      'Sass/SCSS',
      'Less',
      'CSS-in-JS',
      'Styled Components',
      'Emotion',
      'Material-UI',
      'Ant Design',
      'BEM',
    ],
  },
  {
    name: 'Testing Frameworks',
    skills: [
      'Jest',
      'Mocha',
      'Chai',
      'Cypress',
      'Selenium',
      'Playwright',
      'Vitest',
      'Pytest',
      'JUnit',
      'NUnit',
      'TestNG',
      'Jasmine',
    ],
  },
  {
    name: 'API Development',
    skills: [
      'REST API',
      'GraphQL',
      'gRPC',
      'WebSocket',
      'API Gateway',
      'Postman',
      'Insomnia',
      'OpenAPI/Swagger',
      'JSON RPC',
    ],
  },
  {
    name: 'Authentication & Security',
    skills: [
      'JWT',
      'OAuth 2.0',
      'OpenID Connect',
      'SAML',
      'SSL/TLS',
      'Bcrypt',
      'OWASP',
      'Two-Factor Authentication',
      'Auth0',
      'Keycloak',
    ],
  },
  {
    name: 'Real-time Communication',
    skills: [
      'Socket.io',
      'WebRTC',
      'SignalR',
      'Apache Kafka',
      'RabbitMQ',
      'Message Queues',
      'Server-Sent Events',
    ],
  },
  {
    name: 'AI & Machine Learning',
    skills: [
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Scikit-learn',
      'OpenAI API',
      'LangChain',
      'Hugging Face',
      'XGBoost',
      'LightGBM',
      'Pandas',
      'NumPy',
      'Matplotlib',
      'Seaborn',
    ],
  },
  {
    name: 'Development Tools & IDEs',
    skills: [
      'VS Code',
      'Visual Studio',
      'WebStorm',
      'IntelliJ IDEA',
      'PyCharm',
      'Sublime Text',
      'Vim',
      'Emacs',
      'Eclipse',
      'Xcode',
    ],
  },
  {
    name: 'CMS Platforms',
    skills: [
      'WordPress',
      'Drupal',
      'Joomla',
      'Strapi',
      'Contentful',
      'Ghost',
      'Sanity',
      'Payload CMS',
    ],
  },
  {
    name: 'Package Managers & Build Tools',
    skills: [
      'npm',
      'yarn',
      'pnpm',
      'Webpack',
      'Vite',
      'Rollup',
      'Parcel',
      'Gulp',
      'Grunt',
      'Maven',
      'Gradle',
      'pip',
      'Conda',
    ],
  },
  {
    name: 'State Management',
    skills: [
      'Redux',
      'Redux Toolkit',
      'Zustand',
      'Jotai',
      'Recoil',
      'XState',
      'MobX',
      'Context API',
      'Pinia',
      'Vuex',
    ],
  },
  {
    name: 'Monorepo & Project Management',
    skills: [
      'Turborepo',
      'Nx',
      'Lerna',
      'Workspaces',
      'Yarn Workspaces',
    ],
  },
  {
    name: 'Data Visualization',
    skills: [
      'D3.js',
      'Chart.js',
      'ApexCharts',
      'Recharts',
      'Plotly',
      'Tableau',
      'Power BI',
      'Kibana',
      'Grafana',
    ],
  },
  {
    name: 'Search & Analytics',
    skills: [
      'Elasticsearch',
      'Algolia',
      'Solr',
      'Google Analytics',
      'Mixpanel',
      'Amplitude',
      'Segment',
    ],
  },
  {
    name: 'Microservices & Architecture',
    skills: [
      'Microservices',
      'Service Mesh',
      'Istio',
      'Consul',
      'Event Sourcing',
      'CQRS',
      'Serverless',
      'AWS Lambda',
      'Google Cloud Functions',
      'Azure Functions',
    ],
  },
  {
    name: 'Documentation & Knowledge Management',
    skills: [
      'Markdown',
      'Confluence',
      'Notion',
      'GitBook',
      'Docusaurus',
      'Storybook',
      'JSDoc',
      'Swagger/OpenAPI',
    ],
  },
];

export function getAllSkills(): string[] {
  return IT_SKILLS.flatMap((category) => category.skills);
}

export function getSkillsByCategory(categoryName: string): string[] {
  const category = IT_SKILLS.find(
    (cat) => cat.name.toLowerCase() === categoryName.toLowerCase()
  );
  return category?.skills || [];
}

export function searchSkills(query: string): SkillCategory[] {
  const lowerQuery = query.toLowerCase();
  return IT_SKILLS.map((category) => ({
    ...category,
    skills: category.skills.filter((skill) =>
      skill.toLowerCase().includes(lowerQuery)
    ),
  })).filter((category) => category.skills.length > 0);
}
