export interface City {
  name: string;
  districts: string[];
}

export const VIETNAM_CITIES: City[] = [
  {
    name: 'Hà Nội',
    districts: [
      'Hoàn Kiếm',
      'Ba Đình',
      'Hai Bà Trưng',
      'Đống Đa',
      'Cầu Giấy',
      'Thanh Xuân',
      'Hoàng Mai',
      'Long Biên',
      'Bắc Từ Liêm',
      'Tây Hồ',
      'Nam Từ Liêm',
      'Hà Đông',
      'Sơn Tây',
      'Thanh Oai',
      'Thường Tín',
      'Phúc Thọ',
      'Ứng Hòa',
      'Mỹ Đức',
      'Ba Vì',
      'Sóc Sơn',
      'Quốc Oai',
      'Chương Mỹ',
      'Đan Phương',
      'Hoài Đức',
      'Gia Lâm',
      'Đông Anh',
      'Thạch Thất',
      'Mê Linh',
      'Thanh Hà',
    ],
  },
  {
    name: 'TP. Hồ Chí Minh',
    districts: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      'Tân Bình',
      'Tân Phú',
      'Phú Nhuận',
      'Bình Thạnh',
      'Gò Vấp',
      'Bình Tân',
      'Thủ Đức',
      'Bình Chánh',
      'Cần Thơ',
      'Hóc Môn',
      'Nhà Bè',
      'Củ Chi',
    ],
  },
  {
    name: 'Đà Nẵng',
    districts: [
      'Hải Châu',
      'Thanh Khê',
      'Sơn Trà',
      'Ngũ Hành Sơn',
      'Liên Chiểu',
      'Cẩm Lệ',
      'Hòa Vang',
    ],
  },
  {
    name: 'Hải Phòng',
    districts: [
      'Hồng Bàng',
      'Ngô Quyền',
      'Lê Chân',
      'Kiến An',
      'Dương Kiếp',
      'Thủy Nguyên',
      'An Dương',
      'Tiên Lãng',
      'Vĩnh Bảo',
      'Cát Hải',
      'Bạch Long Vĩ',
    ],
  },
  {
    name: 'Cần Thơ',
    districts: [
      'Ninh Kiều',
      'Bình Thủy',
      'Cái Răng',
      'Phong Điền',
      'Thốt Nót',
      'Ô Môn',
      'Vĩnh Thạnh',
    ],
  },
  {
    name: 'An Giang',
    districts: [
      'Long Xuyên',
      'Châu Đốc',
      'Tân Châu',
      'Phú Tân',
      'Chợ Mới',
      'Tịnh Biên',
      'An Phú',
      'Tri Tôn',
    ],
  },
  {
    name: 'Bạc Liêu',
    districts: [
      'Bạc Liêu',
      'Hồng Dân',
      'Vĩnh Lợi',
      'Ba Queo',
      'Cần Đôi',
    ],
  },
  {
    name: 'Bắc Kạn',
    districts: [
      'Bắc Kạn',
      'Pác Nặm',
      'Ba Bể',
      'Ngân Sơn',
      'Nông Cống',
    ],
  },
  {
    name: 'Bắc Giang',
    districts: [
      'Bắc Giang',
      'Lục Ngạn',
      'Sơn Động',
      'Yên Dũng',
      'Tuyên Quang',
      'Lục Nam',
      'Hiệp Hòa',
      'Việt Yên',
    ],
  },
  {
    name: 'Bến Tre',
    districts: [
      'Bến Tre',
      'Châu Thành',
      'Chợ Lách',
      'Mỏ Cày',
      'Ba Tri',
      'Thạnh Phú',
    ],
  },
  {
    name: 'Bình Dương',
    districts: [
      'Thủ Dầu Một',
      'Dĩ An',
      'Thuận An',
      'Bến Cát',
      'Phú Giáo',
      'Bàu Bàng',
      'Tây Ninh',
      'Tân Uyên',
    ],
  },
  {
    name: 'Bình Phước',
    districts: [
      'Đồng Xoài',
      'Thị Xã Bình Long',
      'Bình Phước',
      'Lộc Ninh',
      'Phú Riềng',
      'Chơn Thành',
      'Tân Uyên',
    ],
  },
  {
    name: 'Bình Thuận',
    districts: [
      'Phan Thiết',
      'La Gi',
      'Tuy Phong',
      'Hàm Tân',
      'Hàm Liêu',
      'Tánh Linh',
      'Đức Linh',
      'Tuy Nghĩa',
    ],
  },
  {
    name: 'Cà Mau',
    districts: [
      'Cà Mau',
      'Năm Căn',
      'Mũi Cà Mau',
      'Đầm Dơi',
      'U Minh',
      'Phú Tân',
    ],
  },
  {
    name: 'Cao Bằng',
    districts: [
      'Cao Bằng',
      'Bảo Lâm',
      'Bảo Lạc',
      'Hạ Lang',
      'Quảng Uyên',
      'Thạch An',
      'Hà Quảng',
      'Trùng Kỳ',
      'Nguyên Bình',
      'Mông Dương',
    ],
  },
  {
    name: 'Đắk Lắk',
    districts: [
      'Buôn Ma Thuột',
      'Buôn Hồ',
      'Krông Ana',
      'Krông Búk',
      'Krông Năng',
      'Krông Bông',
      'Cư Mgar',
      'Ea Kar',
      'Lắk',
    ],
  },
  {
    name: 'Đắk Nông',
    districts: [
      'Gia Nghĩa',
      'Đắk Nông',
      'Krông Nô',
      'Tuy Đức',
      'Cư Jut',
    ],
  },
  {
    name: 'Điện Biên',
    districts: [
      'Điện Biên Phủ',
      'Mường Ảng',
      'Nước Ngoài',
      'Tủa Chùa',
      'Mường Nhé',
      'Sơn La',
      'Thanh Uyên',
      'Điện Biên Đông',
      'Mường Lay',
    ],
  },
  {
    name: 'Đồng Nai',
    districts: [
      'Biên Hòa',
      'Long Khánh',
      'Long Thành',
      'Nhơn Trạch',
      'Trảng Bom',
      'Vũng Tàu',
      'Xuân Lộc',
      'Tân Phú',
      'Tà Nung',
    ],
  },
  {
    name: 'Đồng Tháp',
    districts: [
      'Cao Lãnh',
      'Sà Đéc',
      'Tân Hồng',
      'Thanh Bình',
      'Châu Thành',
      'Hồng Ngu',
      'Tháp Mười',
      'Cao Lãnh',
    ],
  },
  {
    name: 'Gia Lai',
    districts: [
      'Pleiku',
      'An Khê',
      'Ayun Pa',
      'Chư Sê',
      'Chư Prông',
      'Đrắk Búk',
      'Kbang',
      'Kông Chro',
      'Krông Pa',
      'La Grai',
      'Mang Yang',
      'Phú Thiện',
    ],
  },
  {
    name: 'Hà Giang',
    districts: [
      'Hà Giang',
      'Vị Xuyên',
      'Yên Minh',
      'Xín Mần',
      'Bắc Mê',
      'Quản Bạ',
      'Đông Văn',
      'Mèo Vạc',
    ],
  },
  {
    name: 'Hà Nam',
    districts: [
      'Phủ Lý',
      'Duy Tiên',
      'Kim Bảng',
      'Bình Lục',
      'Thanh Liêm',
    ],
  },
  {
    name: 'Hà Tĩnh',
    districts: [
      'Hà Tĩnh',
      'Hồng Lĩnh',
      'Thạch Hà',
      'Huỳnh Trân',
      'Kỳ Anh',
      'Lộc Hà',
      'Vũ Quang',
      'Can Lộc',
      'Thạch Thất',
    ],
  },
  {
    name: 'Hải Dương',
    districts: [
      'Hải Dương',
      'Chí Linh',
      'Kinh Môn',
      'Nam Sách',
      'Ninh Giang',
      'Thanh Hà',
      'Tứ Kỳ',
    ],
  },
  {
    name: 'Hòa Bình',
    districts: [
      'Hòa Bình',
      'Tân Lạc',
      'Lương Sơn',
      'Kim Bôi',
      'Cao Phong',
      'Yên Thủy',
      'Đà Bắc',
    ],
  },
  {
    name: 'Hưng Yên',
    districts: [
      'Hưng Yên',
      'Văn Lâm',
      'Văn Giang',
      'Yên Mỹ',
      'Tiên Lữ',
      'Mỹ Hào',
      'Kim Động',
    ],
  },
  {
    name: 'Khánh Hòa',
    districts: [
      'Nha Trang',
      'Cam Ranh',
      'Nha Trang',
      'Cam Lâm',
      'Vạn Ninh',
      'Ninh Hòa',
      'Khánh Sơn',
      'Khánh Vĩnh',
      'Diên Khánh',
    ],
  },
  {
    name: 'Kiên Giang',
    districts: [
      'Rạch Giá',
      'Hà Tiên',
      'Phú Quốc',
      'Kiên Lương',
      'Gò Quao',
      'An Minh',
      'An Biên',
      'Tân Hiệp',
      'Châu Thành',
      'U Minh Thượng',
      'Vĩnh Thuận',
      'Hòn Đất',
    ],
  },
  {
    name: 'Kon Tum',
    districts: [
      'Kon Tum',
      'Đắk Glei',
      'Đắk Tô',
      'Ngọc Hồi',
      'Tu Mơ Rông',
      'Ia H\'Drai',
    ],
  },
  {
    name: 'Lai Châu',
    districts: [
      'Lai Châu',
      'Tam Đường',
      'Mường Tè',
      'Phong Thổ',
      'Nậm Nhùn',
      'Tân Uyên',
      'Sìn Hồ',
    ],
  },
  {
    name: 'Lâm Đồng',
    districts: [
      'Đà Lạt',
      'Đức Trọng',
      'Lâm Hà',
      'Đạo Lạc',
      'Cát Tiên',
      'Di Linh',
      'Bảo Lâm',
      'Thạch Thất',
    ],
  },
  {
    name: 'Lạng Sơn',
    districts: [
      'Lạng Sơn',
      'Chi Lăng',
      'Tràng Định',
      'Văn Quan',
      'Hữu Lũng',
      'Cao Lộc',
      'Bắc Sơn',
      'Công Bình',
    ],
  },
  {
    name: 'Lào Cai',
    districts: [
      'Lào Cai',
      'Sa Pa',
      'Bắc Hà',
      'Bảo Thắng',
      'Bảo Yên',
      'Mường Khương',
      'Si Ma Cai',
      'Văn Bàn',
    ],
  },
  {
    name: 'Long An',
    districts: [
      'Tân An',
      'Cần Đước',
      'Cần Giuộc',
      'Thạnh Hóa',
      'Mỹ Xuyên',
      'Tính Bình',
      'Đức Huệ',
      'Bến Lức',
      'Thủ Thừa',
      'Vĩnh Hưng',
      'Tân Thạnh',
      'Châu Thành',
    ],
  },
  {
    name: 'Nam Định',
    districts: [
      'Nam Định',
      'Mỹ Lộc',
      'Ý Yên',
      'Nghĩa Hưng',
      'Vụ Bản',
      'Xuân Trường',
      'Giao Thủy',
      'Hải Hậu',
    ],
  },
  {
    name: 'Nghệ An',
    districts: [
      'Vinh',
      'Cửa Lò',
      'Anh Sơn',
      'Diễn Châu',
      'Yên Thành',
      'Quỳ Hợp',
      'Quỳ Châu',
      'Tân Kỳ',
      'Tây Giang',
      'Quỳnh Lưu',
      'Hưng Nguyên',
      'Thanh Chương',
      'Nghi Lộc',
      'Kỳ Sơn',
      'Con Cuông',
      'Tân Ưu',
      'Quế Phong',
      'Quế Nước',
    ],
  },
  {
    name: 'Ninh Bình',
    districts: [
      'Ninh Bình',
      'Tam Điệp',
      'Yên Khánh',
      'Yên Mô',
      'Kim Sơn',
      'Hoa Lư',
      'Nho Quan',
    ],
  },
  {
    name: 'Ninh Thuận',
    districts: [
      'Phan Rang-Tháp Chàm',
      'Ninh Hải',
      'Ninh Phước',
      'Thuận Bắc',
      'Thuận Nam',
    ],
  },
  {
    name: 'Phú Thọ',
    districts: [
      'Việt Trì',
      'Phú Thọ',
      'Hạ Hòa',
      'Đoan Hùng',
      'Yên Lập',
      'Thanh Sơn',
      'Tân Sơn',
      'Cửa Ổ',
    ],
  },
  {
    name: 'Phú Yên',
    districts: [
      'Tuy Hòa',
      'Đông Hòa',
      'Tuy An',
      'Đông Xuân',
      'Phú Hòa',
      'Phú Yên',
      'Sơn Hòa',
      'Sông Cầu',
    ],
  },
  {
    name: 'Quảng Bình',
    districts: [
      'Đông Hà',
      'Quảng Trị',
      'Vĩnh Linh',
      'Gio Linh',
      'Đông Hời',
      'Hải Lăng',
      'Con Cuông',
      'Tuyên Hóa',
      'Quảng Ninh',
      'Bố Trạch',
    ],
  },
  {
    name: 'Quảng Nam',
    districts: [
      'Hội An',
      'Tam Kỳ',
      'Duy Xuyên',
      'Điện Bàn',
      'Thăng Bình',
      'Tiên Phước',
      'Phước Sơn',
      'Bắc Trà My',
      'Trà My',
      'Nam Giang',
      'Tây Giang',
      'Đông Giang',
      'Nông Sơn',
      'Thạch Nham',
    ],
  },
  {
    name: 'Quảng Ngãi',
    districts: [
      'Quảng Ngãi',
      'Bình Sơn',
      'Sơn Hà',
      'Sơn Tịnh',
      'Sơn Tây',
      'Ba Tơ',
      'Tư Nghĩa',
      'Lý Sơn',
      'Môn Dương',
      'Trà Khúc',
    ],
  },
  {
    name: 'Quảng Ninh',
    districts: [
      'Hạ Long',
      'Quảng Yên',
      'Cẩm Phả',
      'Móng Cái',
      'Uông Bí',
      'Đông Triều',
      'Yên Hưng',
      'Bình Liêu',
      'Tiên Yên',
      'Vân Đồn',
      'Gành Hào',
      'Cô Tô',
    ],
  },
  {
    name: 'Quảng Trị',
    districts: [
      'Quảng Trị',
      'Đông Hà',
      'Cam Lộ',
      'Gio Linh',
      'Thiên Cầm',
      'Vĩnh Linh',
      'Hải Lăng',
      'Cồn Cỏ',
    ],
  },
  {
    name: 'Sóc Trăng',
    districts: [
      'Sóc Trăng',
      'Bạ Sau',
      'Cù Lao Dung',
      'Kế Sành',
      'Long Phú',
      'Mỹ Tú',
      'Thạnh Trị',
      'Trần Đề',
      'Vĩnh Châu',
      'Châu Thành',
    ],
  },
  {
    name: 'Sơn La',
    districts: [
      'Sơn La',
      'Quỳnh Nhai',
      'Phù Yên',
      'Thuận Châu',
      'Mộc Châu',
      'Yên Châu',
      'Bắc Yên',
      'Tạ Xương',
      'Sốp Cộp',
      'Mai Sơn',
    ],
  },
  {
    name: 'Tây Ninh',
    districts: [
      'Tây Ninh',
      'Tân Biên',
      'Tân Châu',
      'Dương Minh Châu',
      'An Phú',
      'Bến Cầu',
      'Gò Dầu',
      'Hòa Thành',
    ],
  },
  {
    name: 'Thái Bình',
    districts: [
      'Thái Bình',
      'Thái Thụy',
      'Quỳnh Phụ',
      'Hưng Hà',
      'Vũ Thư',
      'Kiến Xương',
      'Đông Hưng',
      'Giao Thủy',
    ],
  },
  {
    name: 'Thái Nguyên',
    districts: [
      'Thái Nguyên',
      'Sơn Dương',
      'Định Hóa',
      'Phú Bình',
      'Đại Từ',
      'Võ Nhai',
      'Chiêm Hóa',
      'Mông Dương',
      'Nông Cống',
    ],
  },
  {
    name: 'Thanh Hóa',
    districts: [
      'Thanh Hóa',
      'Sầm Sơn',
      'Bỉm Sơn',
      'Tĩnh Gia',
      'Hạ Hòa',
      'Hà Trung',
      'Hoằng Hóa',
      'Như Xuân',
      'Quan Hóa',
      'Quy Nhơn',
      'Thạch Thất',
      'Thường Xuân',
      'Yên Định',
      'Nông Cống',
      'Lang Chánh',
      'Thạch Thành',
    ],
  },
  {
    name: 'Thừa Thiên Huế',
    districts: [
      'Huế',
      'A Lưới',
      'Phong Điền',
      'Hương Trà',
      'Phú Lộc',
      'Phú Vang',
      'Nam Đông',
      'Quảng Điền',
    ],
  },
  {
    name: 'Tiền Giang',
    districts: [
      'Mỹ Tho',
      'Gò Công',
      'Tân An',
      'Cái Bè',
      'Cái Lậy',
      'Chợ Gạo',
      'Tân Phước',
      'Nước Mặn',
    ],
  },
  {
    name: 'Trà Vinh',
    districts: [
      'Trà Vinh',
      'Cầu Kè',
      'Cầu Ngang',
      'Châu Thành',
      'Duyên Hải',
      'Tiểu Cần',
      'Vũng Liêm',
      'Trà Ôn',
    ],
  },
  {
    name: 'Tuyên Quang',
    districts: [
      'Tuyên Quang',
      'Chiêm Hóa',
      'Hàm Yên',
      'Nà Hang',
      'Yên Sơn',
    ],
  },
  {
    name: 'Vĩnh Long',
    districts: [
      'Vĩnh Long',
      'Mang Thít',
      'Vĩnh Hưng',
      'Tam Bình',
      'Tân Phước',
      'Bình Minh',
      'Long Hồ',
      'Trà Ôn',
    ],
  },
  {
    name: 'Vĩnh Phúc',
    districts: [
      'Vĩnh Yên',
      'Phúc Yên',
      'Tam Dương',
      'Tam Đảo',
      'Yên Lạc',
      'Sông Công',
      'Lập Thạch',
      'Bình Xuyên',
    ],
  },
  {
    name: 'Yên Bái',
    districts: [
      'Yên Bái',
      'Lục Yên',
      'Văn Yên',
      'Trấn Yên',
      'Sơn Động',
      'Phú Thọ',
      'Trạm Tấu',
      'Văn Chấp',
    ],
  },
];

export function getCityDistricts(cityName: string): string[] {
  const city = VIETNAM_CITIES.find((c) => c.name === cityName);
  return city?.districts || [];
}
